theme: jekyll-theme-cayman
title: Predicting the Outcome of an NBA Game using the Star Players from Each Team
description: Using data from the 2018, 2019, and 2020 NBA Regular season stats from specific players to predict matches.
